# Generated by Django 4.2.4 on 2023-08-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.FloatField(help_text=' minutes')),
                ('ingredients', models.CharField(help_text=' please separate ingredients with commas', max_length=300)),
            ],
        ),
    ]
